import Wrapper from './components/Wrapper';
import './global.css';

export const metadata = {
    title: 'Welcome to account',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body>
                <Wrapper>{children}</Wrapper>
            </body>
        </html>
    );
}
