import './global.css';
import Wrapper from '../components/Wrapper';

export const metadata = {
  title: 'Welcome to e-commerce',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
